disallowed-methods = [
  { path = "futures::future::join_all", reason = "We don't have a replacement for this method yet. Consider extending `SeqJoin` trait." },
  { path = "futures::future::try_join_all", reason = "Use Context.try_join instead." },
]
