[package]
name = "raw-ipa"
version = "0.1.0"
rust-version = "1.57.0"
edition = "2021"

[features]
default = ["debug", "cli"]
cli = ["enable-serde", "structopt", "web-app", "tracing-subscriber"]
debug = ["hex"]
enable-serde = ["serde", "serde_json", "rust-elgamal/enable-serde"]
web-app = ["tokio", "axum", "axum-server", "hyper", "hyper-tls", "tower-http"]
self-signed-certs = ["hyper-tls"]

[dependencies]
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, not 0.10
digest = "0.9"
hex = {version = "0.4", optional = true}
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, so pin this
hkdf = "0.11"
log = "0.4"
rand_core = "0.6"
rand = "0.8"
redis = "0.21.5"
rust-elgamal = "0.4"
serde = {version = "1.0", optional = true}
serde_json = {version = "1.0", optional = true}
# rust-elgamal (via curve25519-dalek-ng) only works with digest 0.9, so pin this
sha2 = "0.9"
structopt = {version = "0.3", optional = true}
thiserror = "1.0"
tracing = "0.1.35"
tokio = { version = "1.19.2", optional = true, features = ["rt", "rt-multi-thread", "macros"] }
axum = { version = "0.5.7", optional = true, features = ["http2"] }
hyper = { version = "0.14.19", optional = true, features = ["client", "h2"] }
hyper-tls = { version = "0.5.0", optional = true }
axum-server = { version = "0.4.0", optional = true, features = ["rustls", "rustls-pemfile", "tls-rustls"] }
tracing-subscriber = { version = "0.3.14", optional = true }
tower-http = { version = "0.3.4", optional = true, features = ["trace"] }




[dev-dependencies]
hex = "0.4"
lazy_static = "1.4.0"

[lib]
name = "raw_ipa"
path = "src/lib.rs"

[[bin]]
name = "ua"
required-features = ["cli"]

[[bin]]
name = "helper"
required-features = ["cli"]
