name: CI
on: [push, pull_request]
jobs:
  rust-check:
    name: Rust Checks
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        name: Build
        with:
          command: build
          args: --tests
# todo: enable this action once Step trait no longer causes release build failures
#      - uses: actions-rs/cargo@v1
#        name: Release Build
#        with:
#          command: build
#          args: --release

      - uses: actions-rs/cargo@v1
        name: Check formatting
        if: ${{ success() || failure() }}
        with:
          command: fmt
          args: --all -- --check

      - uses: actions-rs/cargo@v1
        name: Clippy
        if: ${{ success() || failure() }}
        with:
          command: clippy
          args: --tests -- -D warnings -D clippy::pedantic

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test
